# Generated by Django 5.0.4 on 2024-06-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolInformation',
            fields=[
                ('symbol_id', models.AutoField(primary_key=True, serialize=False)),
                ('market_code', models.CharField(max_length=5)),
                ('symbol_name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_type', models.CharField(max_length=50)),
                ('order_reject_upper', models.FloatField(default=0.0, verbose_name='high')),
                ('order_reject_lower', models.FloatField(default=0.0, verbose_name='low')),
                ('last_day_close', models.FloatField(default=0.0, verbose_name='lcdp')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.symbolinformation')),
            ],
        ),
    ]
