# Generated by Django 5.0.4 on 2024-06-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolinformation',
            name='symbol_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
