# Generated by Django 5.0.4 on 2024-06-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_symbolinformation_symbol_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolinformation',
            name='symbol_code',
            field=models.CharField(default='EMPTY', max_length=20),
        ),
    ]
