# Generated by Django 5.0.4 on 2024-06-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_stockreportentry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreportentry',
            name='date_of_entyry',
            field=models.TextField(default=' '),
        ),
    ]
